"""
Module d'Analyse Prédictive & Sécurité G-code pour l'Atelier 3D de Maverick (Nora G-code Analyzer).
Audite en détail les fichiers .gcode avant lancement sur l'imprimante 3D :
- Détection du trancheur (PrusaSlicer, OrcaSlicer, Cura, Bambu Studio)
- Extraction de la durée estimée, masse de filament (g), longueur (m)
- Températures buse / plateau et hauteur de couche
- Audit de sécurité thermique et mécanique (Zéro collision, zéro décollement)
"""

import os
import re
from pathlib import Path
from typing import Dict, Any, List

def analyze_gcode_file(filepath: str) -> Dict[str, Any]:
    """
    Audite un fichier G-code et retourne un diagnostic technique complet et des recommandations.
    """
    p = Path(filepath)
    if not p.exists() or not p.is_file():
        return {
            "success": False,
            "error": f"Fichier G-code introuvable : {filepath}"
        }

    file_size_mb = round(p.stat().st_size / (1024 * 1024), 2)

    # Paramètres extraits
    slicer = "Trancheur Inconnu"
    print_time_str = "Inconnue"
    filament_g = 0.0
    filament_m = 0.0
    filament_type = "PLA"
    nozzle_temp = 0
    bed_temp = 0
    layer_height = 0.0
    total_layers = 0

    warnings: List[str] = []
    layer_count_pattern = re.compile(r";LAYER:(\d+)|; layer (\d+)|;LAYER_CHANGE")

    # Lecture efficace : les 35 000 premières lignes et les 10 000 dernières
    header_lines = []
    footer_lines = []

    try:
        with open(p, "r", encoding="utf-8", errors="ignore") as f:
            for i, line in enumerate(f):
                if i < 35000:
                    header_lines.append(line)
                else:
                    break

        # Lire la fin si le fichier est volumineux
        if file_size_mb > 2.0:
            with open(p, "r", encoding="utf-8", errors="ignore") as f:
                all_lines = f.readlines()
                footer_lines = all_lines[-10000:]
        else:
            footer_lines = header_lines[-10000:] if len(header_lines) > 10000 else header_lines

    except Exception as e:
        return {"success": False, "error": f"Erreur de lecture : {e}"}

    combined_inspect = header_lines + footer_lines

    for line in combined_inspect:
        line_strip = line.strip()
        lower = line_strip.lower()

        # 1. Trancheur
        if "generated by prusaslicer" in lower:
            slicer = "PrusaSlicer"
        elif "generated by orcaslicer" in lower:
            slicer = "OrcaSlicer"
        elif "generated by cura" in lower or "cura_steamengine" in lower:
            slicer = "UltiMaker Cura"
        elif "generated by bambustudio" in lower:
            slicer = "Bambu Studio"

        # 2. Temps d'impression estimé
        if "estimated printing time" in lower and print_time_str == "Inconnue":
            # ex: ; estimated printing time (normal mode) = 1h 22m 34s
            m = re.search(r"=\s*(.*)", line_strip)
            if m:
                print_time_str = m.group(1).strip()
        elif lower.startswith(";time:") and print_time_str == "Inconnue":
            try:
                sec = int(line_strip.split(":")[1])
                h = sec // 3600
                mn = (sec % 3600) // 60
                print_time_str = f"{h}h {mn}m"
            except Exception:
                pass

        # 3. Consommation de filament
        if "filament used [g]" in lower and filament_g == 0.0:
            m = re.search(r"=\s*([0-9\.]+)", line_strip)
            if m:
                filament_g = round(float(m.group(1)), 1)
        if "filament used [mm]" in lower and filament_m == 0.0:
            m = re.search(r"=\s*([0-9\.]+)", line_strip)
            if m:
                filament_m = round(float(m.group(1)) / 1000.0, 2)
        elif lower.startswith(";filament used [m]") and filament_m == 0.0:
            m = re.search(r"=\s*([0-9\.]+)", line_strip)
            if m:
                filament_m = round(float(m.group(1)), 2)

        # 4. Type de filament
        if "filament_type" in lower:
            m = re.search(r"=\s*([a-zA-Z0-9_\-]+)", line_strip)
            if m:
                filament_type = m.group(1).strip().upper()

        # 5. Hauteur de couche
        if "layer_height" in lower and layer_height == 0.0:
            m = re.search(r"=\s*([0-9\.]+)", line_strip)
            if m:
                layer_height = float(m.group(1))

        # 6. Températures G-code (M104, M109 pour buse / M140, M190 pour plateau)
        if nozzle_temp == 0:
            m_nozzle = re.search(r"M10[49]\s+S(\d+)", line_strip)
            if m_nozzle:
                nozzle_temp = int(m_nozzle.group(1))
        if bed_temp == 0:
            m_bed = re.search(r"M1[49]0\s+S(\d+)", line_strip)
            if m_bed:
                bed_temp = int(m_bed.group(1))

        # 7. Total couches
        if "total layers count" in lower and total_layers == 0:
            m = re.search(r"=\s*(\d+)", line_strip)
            if m:
                total_layers = int(m.group(1))

    # Audit de sécurité prédictif
    safety_score = 100

    if nozzle_temp > 285:
        warnings.append(f"⚠️ Température de buse très élevée ({nozzle_temp}°C). Risque de dégradation du tube PTFE si non Full Metal.")
        safety_score -= 20
    elif nozzle_temp < 180 and nozzle_temp > 0:
        warnings.append(f"⚠️ Température de buse basse ({nozzle_temp}°C). Risque de sous-extrusion ou de buse bouchée.")
        safety_score -= 15

    if filament_type in ["PETG", "ABS", "ASA"] and bed_temp < 60 and bed_temp > 0:
        warnings.append(f"⚠️ Plateau à {bed_temp}°C pour du {filament_type}. Risque majeur de décollement / Warping (80-100°C recommandé).")
        safety_score -= 25

    if bed_temp == 0:
        warnings.append("ℹ️ Aucun chauffage de plateau détecté dans le G-code (normal uniquement pour PLA sur plateau froid ou TPU).")

    if filament_g == 0.0 and filament_m > 0:
        # Estimation approximative PLA (1.24 g/cm3, 1.75mm -> ~3.0g par mètre)
        filament_g = round(filament_m * 3.0, 1)

    return {
        "success": True,
        "filename": p.name,
        "file_size_mb": file_size_mb,
        "slicer": slicer,
        "estimated_time": print_time_str,
        "filament_weight_g": filament_g,
        "filament_length_m": filament_m,
        "filament_type": filament_type,
        "nozzle_temp_c": nozzle_temp,
        "bed_temp_c": bed_temp,
        "layer_height_mm": layer_height or 0.20,
        "total_layers": total_layers,
        "safety_score": max(20, safety_score),
        "safety_verdict": "SÉCURISÉ & PRÊT À IMPRIMER" if safety_score >= 80 else "ATTENTION REQUISE",
        "warnings": warnings
    }

if __name__ == "__main__":
    print("Test de l'Analyseur G-code Nora...")
    dummy_gcode = Path("test_sample.gcode")
    with open(dummy_gcode, "w", encoding="utf-8") as f:
        f.write("; generated by PrusaSlicer 2.7.1\n")
        f.write("; estimated printing time (normal mode) = 2h 15m 10s\n")
        f.write("; filament used [g] = 34.5\n")
        f.write("; filament used [mm] = 11500.0\n")
        f.write("; filament_type = PETG\n")
        f.write("; layer_height = 0.20\n")
        f.write("; total layers count = 210\n")
        f.write("M190 S85\n")
        f.write("M109 S240\n")
        f.write("G1 X10 Y10 Z0.2 E1.0\n")
    
    res = analyze_gcode_file(str(dummy_gcode))
    print(f"Résultat analyse :\n{res}")
    dummy_gcode.unlink(missing_ok=True)
